### ISSUE TITLE
Hard-coded IP for upload

### ISSUE THREAD

**Issue by garrison** [simonschllng/rm-sync#7]
There is a hard-coded IP address at https://github.com/simonschllng/rm-sync/blob/931d5cac8723425887386f1f496a91874a2a047b/rM-sync.sh#L101
Presumably, `$RMIP` should be used instead.

**Comment by garrison** [comment]
Actually, I might have filed this in error, since it seems the script is only meant to work over USB, and the upload feature works only over USB, with that hard-coded IP address, from what I now understand.

**Comment by simonschllng** [comment]
rM has a hard codes IP and so does the script.
